# XcodeGen project specification for MLXR
# Generate Xcode project with: xcodegen generate
# Install xcodegen: brew install xcodegen

name: MLXR

options:
  bundleIdPrefix: com.mlxr
  deploymentTarget:
    macOS: "13.0"
  developmentLanguage: swift
  createIntermediateGroups: true
  groupSortPosition: top

settings:
  base:
    MARKETING_VERSION: "0.1.0"
    CURRENT_PROJECT_VERSION: "1"
    SWIFT_VERSION: "5.9"
    MACOSX_DEPLOYMENT_TARGET: "13.0"
    ENABLE_HARDENED_RUNTIME: YES
    COMBINE_HIDPI_IMAGES: YES
    SDKROOT: macosx

targets:
  MLXR:
    type: application
    platform: macOS
    deploymentTarget: "13.0"

    sources:
      - path: MLXR/App
        name: App
      - path: MLXR/Bridge
        name: Bridge
      - path: MLXR/Controllers
        name: Controllers
      - path: MLXR/Daemon
        name: Daemon
      - path: MLXR/Services
        name: Services
      - path: MLXR/Views
        name: Views

    settings:
      base:
        PRODUCT_NAME: MLXR
        PRODUCT_BUNDLE_IDENTIFIER: com.mlxr.MLXR
        INFOPLIST_FILE: MLXR/Info.plist
        CODE_SIGN_ENTITLEMENTS: MLXR/MLXR.entitlements
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: ""
        CODE_SIGN_IDENTITY: "-"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/../Frameworks"
        SWIFT_EMIT_LOC_STRINGS: YES
        GENERATE_INFOPLIST_FILE: NO

    scheme:
      testTargets:
        - MLXRTests
      gatherCoverageData: true

    dependencies:
      - framework: WebKit.framework
        embed: false
      - framework: Foundation.framework
        embed: false
      - framework: AppKit.framework
        embed: false
      - framework: Security.framework
        embed: false
      - framework: ServiceManagement.framework
        embed: false
      - package: Sparkle
        product: Sparkle

  MLXRTests:
    type: bundle.unit-test
    platform: macOS
    deploymentTarget: "13.0"

    sources:
      - path: MLXRTests
        name: Tests

    settings:
      base:
        PRODUCT_NAME: MLXRTests
        PRODUCT_BUNDLE_IDENTIFIER: com.mlxr.MLXRTests
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: ""
        GENERATE_INFOPLIST_FILE: YES
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/../Frameworks @loader_path/../Frameworks"

    dependencies:
      - target: MLXR

packages:
  Sparkle:
    url: https://github.com/sparkle-project/Sparkle
    from: "2.5.0"

schemes:
  MLXR:
    build:
      targets:
        MLXR: all
        MLXRTests: [test]
    run:
      config: Debug
    test:
      config: Debug
      gatherCoverageData: true
      targets:
        - MLXRTests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
